stages:
  get_rnd2_data:
    cmd: tar -xzvfOrcasoundLab07052019_PodCastround2.tar.gz
    deps:
    - OrcasoundLab07052019_PodCastRound2.tar.gz
    outs:
    - Round2_OS_07_05:
        cache: false
  get_rnd3_data:
    cmd: tar -xzvfOrcasoundLab09272017_PodCastRound3.tar.gz
    deps:
    - OrcasoundLab09272017_PodCastRound3.tar.gz
    outs:
    - Round3_OS_09_27_2017:
        cache: false
  get_test_data:
    cmd: tar -xzvfOrcasoundLab09272017_Test.tar.gz
    deps:
    - OrcasoundLab09272017_Test.tar.gz
    outs:
    - OrcasoundLab09272017_Test:
        cache: false
  get_test_data2:
    cmd: tar -xzvfOS_SVeirs_07_05_2019_08_24_00.tar.gz
    deps:
    - OS_SVeirs_07_05_2019_08_24_00.tar.gz
    outs:
    - test_data:
        cache: false
  extract_calls_rnd2:
    cmd: python preprocess.py --tsv_path Round2_OS_07_05/train.tsv  --files_dir Round2_OS_07_05/wav --call_time 2 --output_dir extracted-calls --reduce_noise
    deps:
    - preprocess.py
    - Round2_OS_07_05
    outs:
    - extracted-calls/1:
        cache: false
    - extracted-calls/0:
        cache: false
